[project]
name = "scheduler_config_editor"
version = "0.1.1"
description = "A program that allows for JSON config modification and schedule generation."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "course-constraint-scheduler",
    "click",
    "click-shell",
    "PyQt6",
    "tabulate",
    "types-tabulate",
    "dotenv",
    "langchain-openai",
    "langchain",
    "langgraph",
    "reportlab"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "ty",
    "ruff"
]

[tool.uv]
package = true

[project.scripts]
sce = "scheduler_config_editor.main:main"

# The purpose of this section is to suppress a specific deprecation warning.
# Click_shell has a deprecated feature that is still in use, and this warning clutters the test output.
[tool.pytest.ini_options]
filterwarnings = [
  "ignore:'protected_args' is deprecated and will be removed in Click 9.0:DeprecationWarning:click_shell.core",
  "ignore:The 'frozen' attribute with value True was provided to the `Field\\(\\)` function:UserWarning:pydantic._internal._generate_schema"
]
